# Base Image
FROM python:3.10.12-slim-buster

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# User directory
RUN mkdir -p /home/app

# Create non-root user
RUN groupadd --gid 1001 app && \
    useradd --uid 1001 --gid app --home /home/app app

# install pipenv
RUN pip install pipenv

# Create directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/eapp
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
RUN mkdir $APP_HOME/mediafiles
WORKDIR $APP_HOME

# installing dependecies
COPY Pipfile Pipfile.lock $APP_HOME

RUN pipenv install --dev --system

COPY . $APP_HOME

RUN chown -R app:app $APP_HOME

USER app
